INSERT INTO answer_options (identifier,text,group_id) VALUES
('6OG1','Strongly Disagree',(SELECT id FROM answer_groups WHERE identifier LIKE '6OG')),
('6OG2','Disagree',(SELECT id FROM answer_groups WHERE identifier LIKE '6OG')),
('6OG3','Neutral',(SELECT id FROM answer_groups WHERE identifier LIKE '6OG')),
('6OG4','Agree',(SELECT id FROM answer_groups WHERE identifier LIKE '6OG')),
('6OG5','Strongly Agree',(SELECT id FROM answer_groups WHERE identifier LIKE '6OG')),
('6OG6','I do not know',(SELECT id FROM answer_groups WHERE identifier LIKE '6OG')),
('YNG1','TRUE',(SELECT id FROM answer_groups WHERE identifier LIKE 'YNG')),
('YNG2','FALSE',(SELECT id FROM answer_groups WHERE identifier LIKE 'YNG')),
('MTG1','Advertising',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG2','Analytics',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG3','Apps (e.g. Mobile or Social)',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG4','Big Data',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG5','Cloud Computing',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG6','Developer Tool',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG7','E-Commerce',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG8','Education',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG9','Enterprise Software',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG10','Finances and Administration',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG11','Fashion',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG12','Games',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG13','Healthcare & Life Sciences',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG14','Internet of Things',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG15','Personal Health & Welfare',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG16','Media',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG17','Mobile',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG18','Payments',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG19','Retail',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG20','SaaS',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG21','Sales & Marketing',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG22','Social',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG23','Fin Tech',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG24','Block Chain',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('MTG25','Other',(SELECT id FROM answer_groups WHERE identifier LIKE 'MTG')),
('SPG1','Concept',(SELECT id FROM answer_groups WHERE identifier LIKE 'SPG')),
('SPG2','In Development',(SELECT id FROM answer_groups WHERE identifier LIKE 'SPG')),
('SPG3','Working Prototype',(SELECT id FROM answer_groups WHERE identifier LIKE 'SPG')),
('SPG4','Functional product with Limited Users',(SELECT id FROM answer_groups WHERE identifier LIKE 'SPG')),
('SPG5','Functional Product with High Growth',(SELECT id FROM answer_groups WHERE identifier LIKE 'SPG')),
('SPG6','Mature Product',(SELECT id FROM answer_groups WHERE identifier LIKE 'SPG')),
('PTG1','Software (non - web)',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG2','Web',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG3','Mobile',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG4','Hardware',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG5','Nanotechnology',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG6','Biotechnology',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG7','Consulting',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG8','Physical Inventory',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG9','Clean Tech',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG10','Medical Instrument',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG11','Production Technology',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG12','E-Commerce / M-Commerce',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG13','Content / Media',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PTG14','Other',(SELECT id FROM answer_groups WHERE identifier LIKE 'PTG')),
('PPG1','I prefer not to disclose',(SELECT id FROM answer_groups WHERE identifier LIKE 'PPG')),
('PPG2','Not profitable yet - expected in less than 6 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'PPG')),
('PPG3','Not profitable yet - expected in more than 6 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'PPG')),
('PPG4','For less than 1 month',(SELECT id FROM answer_groups WHERE identifier LIKE 'PPG')),
('PPG5','For the last 6 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'PPG')),
('PPG6','For the last 18 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'PPG')),
('CSG1','Discovering what our product is going to be',(SELECT id FROM answer_groups WHERE identifier LIKE 'CSG')),
('CSG2','Discovering who our customers are / what our product is going to be',(SELECT id FROM answer_groups WHERE identifier LIKE 'CSG')),
('CSG3','Validating that our customers actually want our product',(SELECT id FROM answer_groups WHERE identifier LIKE 'CSG')),
('CSG4','Making our customer acquisition process more efficient / streamlining the product',(SELECT id FROM answer_groups WHERE identifier LIKE 'CSG')),
('CSG5','Scaling the company / aggressively driving user growth',(SELECT id FROM answer_groups WHERE identifier LIKE 'CSG')),
('CSG6','Focusing on profit maximization / expanding the product',(SELECT id FROM answer_groups WHERE identifier LIKE 'CSG')),
('CSG7','Adding complementary products / expanding the product / diversifying the portfolio in order to enter new markets',(SELECT id FROM answer_groups WHERE identifier LIKE 'CSG')),
('DPSG1','Less than 1 month',(SELECT id FROM answer_groups WHERE identifier LIKE 'DPSG')),
('DPSG2','1 - 3 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'DPSG')),
('DPSG3','3 -  6 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'DPSG')),
('DPSG4','6 - 9 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'DPSG')),
('DPSG5','9 - 12 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'DPSG')),
('DPSG6','Over 12 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'DPSG')),
('MG1','You want to make a good living (4 hour workweek style)',(SELECT id FROM answer_groups WHERE identifier LIKE 'MG')),
('MG2','You have an idea',(SELECT id FROM answer_groups WHERE identifier LIKE 'MG')),
('MG3','Create a Quick flip (Clone of an existing product, but just a tad better/cheaper/faster/...)',(SELECT id FROM answer_groups WHERE identifier LIKE 'MG')),
('MG4','You want to build a great product (iPhone)',(SELECT id FROM answer_groups WHERE identifier LIKE 'MG')),
('MG5','You have a technology',(SELECT id FROM answer_groups WHERE identifier LIKE 'MG')),
('MG6','You want to change the World (Google, Facebook)',(SELECT id FROM answer_groups WHERE identifier LIKE 'MG')),
('MG7','You have a passion',(SELECT id FROM answer_groups WHERE identifier LIKE 'MG')),
('FPG1','Less than 3 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'FPG')),
('FPG2','3 - 6 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'FPG')),
('FPG3','6 - 12 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'FPG')),
('FPG4','12 - 18  months',(SELECT id FROM answer_groups WHERE identifier LIKE 'FPG')),
('FPG5','18 - 36 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'FPG')),
('FPG6','Over 36 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'FPG')),
('FPG7','N/A, there was a single Founder',(SELECT id FROM answer_groups WHERE identifier LIKE 'FPG')),
('SVPG1','I have never lived in Silicon Valley',(SELECT id FROM answer_groups WHERE identifier LIKE 'SVPG')),
('SVPG2','About 1 month',(SELECT id FROM answer_groups WHERE identifier LIKE 'SVPG')),
('SVPG3','About 3 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'SVPG')),
('SVPG4','About 6 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'SVPG')),
('SVPG5','About 12 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'SVPG')),
('SVPG6','Over 12 months',(SELECT id FROM answer_groups WHERE identifier LIKE 'SVPG')),
('ARG1','Yes, I certify that these results are accurate',(SELECT id FROM answer_groups WHERE identifier LIKE 'ARG')),
('ARG2','No, I just wanted to check out the questions',(SELECT id FROM answer_groups WHERE identifier LIKE 'ARG')),
('TG1','Textarea',(SELECT id FROM answer_groups WHERE identifier LIKE 'TG')),
('MRG1','0',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG2','0 - 1K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG3','1K- 2K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG4','2K - 3K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG5','3K - 4K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG6','4K - 5K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG7','5K - 6K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG8','6K - 7K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG9','7K - 8K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG10','8K - 9K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG11','9K - 10K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG12','11K - 15K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG13','16K - 20K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG14','21K - 25K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG15','26K - 30K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG16','31K - 35K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG17','36K - 40K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG18','41K - 45K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG19','46K - 50K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG')),
('MRG20','Over 50K',(SELECT id FROM answer_groups WHERE identifier LIKE 'MRG'));